# Generated by Django 3.1.4 on 2020-12-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='time_zone_offset',
            new_name='offset',
        ),
        migrations.AddField(
            model_name='country',
            name='offset_string',
            field=models.CharField(default='+00:00', max_length=7, verbose_name='offset string'),
        ),
    ]
